# Generated by Django 2.0.5 on 2018-07-13 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_items_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='book_author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='book_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 16, 0, 44, 78612, tzinfo=utc)),
        ),
    ]
