# Generated by Django 2.0.5 on 2018-07-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20180713_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
