# Generated by Django 2.0.5 on 2018-07-13 16:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0004_auto_20180713_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_author', models.CharField(max_length=20)),
                ('book_image', models.ImageField(upload_to='books')),
                ('semester', models.CharField(max_length=5)),
                ('branch', models.CharField(max_length=5)),
                ('cost', models.IntegerField()),
                ('published_date', models.DateTimeField(default=datetime.datetime(2018, 7, 13, 16, 5, 17, 294792, tzinfo=utc))),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sellers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
