# Generated by Django 2.0.5 on 2018-07-14 04:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20180714_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 4, 34, 38, 308619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 4, 34, 38, 308619, tzinfo=utc)),
        ),
    ]
