# Generated by Django 2.0.5 on 2018-07-15 08:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0008_auto_20180714_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(default=datetime.datetime(2018, 7, 15, 8, 26, 6, 881783, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='addcart',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addCart', to='mainApp.Items'),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 8, 26, 6, 881783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 8, 26, 6, 881783, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mainApp.Items'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
