# Generated by Django 2.0.5 on 2018-07-15 13:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20180715_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 13, 2, 32, 45838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 13, 2, 32, 45838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mainApp.Items'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 13, 2, 32, 45838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL),
        ),
    ]
